# Generated by Django 3.2.4 on 2021-07-02 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='blabla',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='name',
        ),
    ]
