# Generated by Django 3.2.4 on 2021-07-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210702_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blabla',
            field=models.CharField(max_length=100),
        ),
    ]
