# Generated by Django 3.2.4 on 2021-07-05 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_post_blabla'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='blabla',
            new_name='customerid',
        ),
    ]
