# Generated by Django 3.2.4 on 2021-07-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_blabla_post_customerid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='customerid',
        ),
        migrations.AddField(
            model_name='post',
            name='access',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='age',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='customerId',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='customerNo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='tcNo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
